### ISSUE TITLE
Unregistered task 

### ISSUE THREAD

**Issue by lopesrb** [django-haystack/celery-haystack#34]
I am getting this error after saving a model

Received unregistered task of type u'celery_haystack.tasks.CeleryHaystackSignalHandler

**Comment by barseghyanartur** [comment]
I'm having the same problem.

I'm using redis broker and result backend.

Full source code is public on bitbucket: https://bitbucket.org/barseghyanartur/django-haystack-celery-redis-test/src/ec7d84c91f16?at=default

celeryconfig.py
--------------------
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_ACCEPT_CONTENT=['json']
    CELERY_TIMEZONE = 'Europe/Oslo'
    CELERY_ENABLE_UTC = True

I start celery like this:

    celery worker -l DEBUG -B

Traceback
--------------
Received unregistered task of type 'celery_haystack.tasks.CeleryHaystackSignalHandler'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{'eta': None, 'args': ['update', 'foo.mymodel.6'], 'taskset': None, 'timelimit': [None, None], 'callbacks': None, 'utc': True, 'chord': None, 'expires': None, 'task': 'celery_haystack.tasks.CeleryHaystackSignalHandler', 'errbacks': None, 'id': 'd66e894a-b447-459c-8ff5-0a73e8f5ed3c', 'retries': 0, 'kwargs': {}} (311b)
Traceback (most recent call last):
  File "/home/user/.virtualenvs/django-celery-redis-test/lib/python3.4/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: 'celery_haystack.tasks.CeleryHaystackSignalHandler'

Please, help!

**Comment by atugushev** [comment]
Sorry for necroposting, just for the record: the following setting fixes the problem: 
`CELERY_IMPORTS = ('celery_haystack.tasks',)`
