### ISSUE TITLE
Celery-Haystack: Search Index not being updated with the latest values

### ISSUE THREAD

**Issue by Alexerson** [django-haystack/celery-haystack#40]
Hello, I'm having the same issue as described here: http://stackoverflow.com/questions/24223369/celery-haystack-search-index-not-being-updated-with-the-latest-values
(some version diffs)

You are mentionning that this lib is not compatible with celery 3.1. Can you explain why ?

I'm using celery v3.1.17, django-celery v3.1.16, django-celery-transactions v0.2.0, django-haystack v2.3.1, celery-haystack v0.8 along with the elastcisearch, rabbitmq and postgresql.

The indexes are getting updated, but not with the latest values. Assume the current value in DB as 'x'. Now if I change this value to 'y', the DB is updating properly with 'y' and also I checked the 'instance' information passed on post save, it is good, but the index is being updated by 'x'. Now, if I change the value from 'y' to 'z', the DB and post save information are still good, but the index is being updated with 'y' instead of 'z'.

The DB commits are based on transactions.

It looks like the information that the 'celery-haystack' task is getting from the DB is the old one. I also did check that the Tasks are being created from "djcelery_transactions.PostTransactionTask".

**Comment by cboothe** [comment]
Same issue here. I would rather not downgrade my celery dependencies.

**Comment by codedre** [comment]
Same issue, has anyone found a solution?

**Comment by avgoeid** [comment]
I have the same issue.

**Comment by Alexerson** [comment]
Not using this lib anymore (this ticket refers to old libs anyway)
