### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by madEng84** [django-haystack/celery-haystack#57]
This is the first time I'm using celery-haystack, but not the first with celery and django-celery

in my settings i put:

```
BROKER_URL = 'django://'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
HAYSTACK_SIGNAL_PROCESSOR = 'celery_haystack.signals.CelerySignalProcessor'

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.mysql',
        'ENGINE': 'transaction_hooks.backends.mysql',
        ...
}}
```

The error is

> [Errno 61] Connection refused
> Exception Location:   /Users/macmini1/Workspace/LastMinuteFundRaising/site-packages/virtualenv/amqp/transport.py in **init**, line 95

I don't understand why in the stacktrace i see :

`/Users/macmini1/Workspace/LastMinuteFundRaising/site-packages/virtualenv/kombu/connection.py in connection`

`742 : self._connection = self._establish_connection()`
where self is
`<Connection: amqp://guest:**@127.0.0.1:5672// at 0x110d04250>`

.. even if my BROKER_URL is 'django://'

I'm using
django==1.8.11
celery==3.1.23
celery-haystack==0.10
django-celery==3.1.17

Any help is appreciated

**Comment by stefanw** [comment]
What command are you running? This doesn't look like a `celery-haystack` problem, but like a `celery` misconfigured execution.

**Comment by madEng84** [comment]
Hi @stefanw thank you for the fast response.
I think you are right but I don't understand where the problem is..

I created my celery.py module inside the package project/celery_apps, as I do for any other project without haystack feature, with this code:

```
from __future__ import absolute_import
import os
import sys
from celery.app import shared_task

# Import local site-packages
PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','..')
SITE_PACKAGES = os.path.join(PATH, 'site-packages')

if os.path.isdir(SITE_PACKAGES):
    # insert every package listed in site-packages directory
    for pkg in os.listdir(SITE_PACKAGES):
        sys.path.insert(0, os.path.join(SITE_PACKAGES, pkg))

sys.path.insert(0, PATH)

try:
    import project.local_pythonpath #Where I add my VIRTUAL_ENV_SITEPACKAGES to django's Site
except ImportError:
    pass

from django.conf import settings
from celery import Celery, task
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')

#The first argument to Celery is the name of the current module,
#  this is needed so that names can be automatically generated, 
#the second argument is the broker keyword argument which specifies 
#  the URL of the message broker you want to use
#  es. Celery('project',broker='amqp://localhost//') if RabbitMQ
#  es. Celery('project',broker='redis://localhost//') if Redis
#  es. Celery('project') if Kombu
app = Celery('project')

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.task
def add(x, y):
    return x + y
```

I run my celery daemon with this command (with virtualenv activated):

> celery -A project.celery_apps.celery worker -l info

and i can see in the shell:

> [tasks]
>   . celery_haystack.tasks.CeleryHaystackSignalHandler
>   . celery_haystack.tasks.CeleryHaystackUpdateIndex
>   . project.celery_apps.celery.add

as I expected

If i run inside in my python project's shell (with virtualenv activated):

> from project.celery_apps.celery import add
> x = add.delay(5,6)

It works fine.

when I save a model associated with a search index i can see the error of this topic

celery-haystack's task's are declared in a different manner so is difficult for me to understand where connection is estabilished and why amqp is taken.. maybe I have buypassed some rows in documentation for autodiscovered apps' settings.

I think my question is out-of-topic, out-of-package, but any help is appreciated 
Thanks in advance

**Comment by stefanw** [comment]
Your `celery.py` looks very much unlike [the one from the docs](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) (including sys path hacks which shouldn't be necessary in a Django project). This is not a `celery-haystack` problem, please ask on something like stackoverflow.com.

**Comment by madEng84** [comment]
I resolved with this workaround:

I put these rows in my celery_apps/**init**.py

```
from celery import Celery
app_celery_haystack = Celery('celery_haystack')
app_celery_haystack.config_from_object('django.conf:settings')
```

Hope this helps
