### ISSUE TITLE
Error importing module celery_haystack.tasks: "No module named 'celery'"

### ISSUE THREAD

**Issue by ShubhamSarda** [django-haystack/celery-haystack#69]
Got This Error **Error importing module celery_haystack.tasks: "No module named 'celery'"** During Adding Field Through Admin. 

Using Django - 1.10.8

**Comment by stefanw** [comment]
You need to install the  `celery` dependency as listed under requirements in the README.

**Comment by ShubhamSarda** [comment]
Already Followed All Step. Still Error's On Admin Side.

**Comment by stefanw** [comment]
You may have named your celery config module `celery` and tried importing it with an absolute path.
 [Does  this answer on  StackOverflow help?](https://stackoverflow.com/questions/19577172/celery-worker-error-importerror-no-module-named-celery)
