### ISSUE TITLE
Missing model instances when updating index

### ISSUE THREAD

**Issue by tpcross** [django-haystack/celery-haystack#7]
Sometimes getting errors like this after inserting indexed models into the database:

ERROR/PoolWorker-1] celery_haystack.tasks.CeleryHaystackSignalHandler[68155761-281f-49c1-b2e9-7c31111491c3]: Couldn't load model instance with pk #2320. Somehow it went missing?

The model exists in the database upon later inspection. Using django with PostgreSQL.

Suspected cause is the task is being executed before the database transaction is committed, so the background task can't find the row due to isolation

The task should probably be queued after the trxn is committed, although this might be tricky because it's in a signal handler.

Possible fix might be to use chrisdoble/django-celery-transactions or similar which holds the enqueued task until post commit
Or a workaround could be to use ETA/countdown feature when queuing the task.

**Comment by GabrielDumbrava** [comment]
Hi guys,
I'm trying to use your fix but I get:
```
[2017-06-12 17:25:10,117: ERROR/MainProcess] Received unregistered task of type 'some_app.search_indexes.CeleryHaystackPostTrxnSignalHandler'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
